config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :qualificacoes
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  VotaPrato::Application.routes.draw do
  resources :comentarios
  resources :qualificacoes
  resources :clientes
    match 'inicio', controller: 'restaurantes', action: 'index', via: 'get'
  end

  VotaPrato::Application.routes.draw do
  resources :comentarios
  resources :qualificacoes
  resources :clientes
    match 'ola' => 'ola_mundo#index', via: 'get'
    #match 'rack', :to => proc{|env| [200, {"Content-Type" => "text/html"}, ["App Rack numa rota Rails"]]}

  end

  resources :restaurantes

end

app/models/cliente.rb
class Cliente < ApplicationRecord
  validates_presence_of :nome, message: " - deve ser preenchido"

  validates_uniqueness_of :nome, message: " - nome já cadastrado"

  validates_numericality_of :idade, greater_than: 0,
                              less_than: 100,
                              message: " - deve ser um número entre 0 e 100"

  has_many :qualificacoes

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :idade)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(cliente) do |f| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :idade %>
    <%= f.number_field :idade %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.idade %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <!--<td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @cliente.idade %>
</p>

<%= link_to "Nova qualificação", controller: "qualificacoes",
                                 action: "new",
                                 cliente: @cliente %>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>